import type { SettingTextDict } from "../../../types";

/** 设置面板「文件」页词条。键为 setting path。 */
export const FILES_SETTINGS: SettingTextDict = {
	"edit.mode": {
		label: "编辑模式",
		description: "选择编辑工具变体（replace、patch、hashline 或 apply_patch）",
	},
	"edit.fuzzyMatch": {
		label: "模糊匹配",
		description: "对空白差异采纳高置信度的模糊匹配",
	},
	"edit.fuzzyThreshold": {
		label: "模糊匹配阈值",
		description: "接受模糊匹配所需的相似度阈值（0-1）",
		options: {
			"0.85": { label: "0.85", description: "宽松" },
			"0.90": { label: "0.90", description: "适中" },
			"0.95": { label: "0.95", description: "默认" },
			"0.98": { label: "0.98", description: "严格" },
		},
	},
	"edit.streamingAbort": {
		label: "预览失败时中止",
		description: "补丁预览失败时中止流式编辑工具调用",
	},
	"edit.blockAutoGenerated": {
		label: "阻止编辑自动生成文件",
		description: "阻止编辑看起来是自动生成的文件（protoc、sqlc、swagger 等）",
	},
	"edit.enforceSeenLines": {
		label: "强制已读行校验",
		description: "拒绝锚定在此前 read/search 未完整展示过的行上的编辑",
	},
	readLineNumbers: {
		label: "行号",
		description: "read 工具输出默认前置行号",
	},
	"read.defaultLimit": {
		label: "默认读取行数上限",
		description: "agent 调用 read 未指定 limit 时返回的默认行数",
		options: {
			"200": { label: "200 行" },
			"300": { label: "300 行" },
			"500": { label: "500 行" },
			"1000": { label: "1000 行" },
			"5000": { label: "5000 行" },
		},
	},
	"read.renderMarkdown": {
		label: "Markdown 预览",
		description: "将 Markdown 读取结果渲染为格式化的终端 Markdown 预览，而非原始源码",
	},
	"read.summarize.enabled": {
		label: "结构化摘要",
		description: "read 未指定选择器时返回结构化代码摘要",
	},
	"read.summarize.prose": {
		label: "文本摘要",
		description: "对 Markdown 与纯文本读取也返回结构化摘要",
	},
	"read.summarize.minBodyLines": {
		label: "摘要正文折叠行数",
		description: "多行主体或字面量在被摘要折叠前所需的最小长度",
	},
	"read.summarize.minCommentLines": {
		label: "摘要注释折叠行数",
		description: "多行块注释在被摘要折叠前所需的最小长度",
	},
	"read.summarize.minTotalLines": {
		label: "摘要触发文件最小行数",
		description: "总行数少于此值的文件将逐字读取，而不做结构化摘要",
	},
	"read.summarize.unfoldUntil": {
		label: "摘要展开目标行数",
		description: "对可折叠区间做 BFS 展开，直到摘要可见行数达到该值。0 表示只保留最外层折叠。",
	},
	"read.summarize.unfoldLimit": {
		label: "摘要展开行数上限",
		description:
			"BFS 展开摘要时的硬性行数上限。若某次展开会使已显示行数超过该值，则跳过该展开（该区间保持折叠），并继续展开其余区间。",
	},
	"read.toolResultPreview": {
		label: "内联读取预览",
		description: "在会话记录中内联渲染 read 工具结果，而非摘要行",
	},
	"lsp.enabled": {
		label: "LSP",
		description: "启用 lsp 工具以获取代码智能功能（定义、引用、诊断、重命名）",
	},
	"lsp.lazy": {
		label: "LSP 惰性启动",
		description: "在首次使用时（调用 lsp 工具或编辑匹配文件类型）才启动语言服务器，而非在会话启动时",
	},
	"lsp.shared": {
		label: "共享语言服务器",
		description: "通过守护进程 broker 让同一项目的多个 omp 实例共享一个语言服务器（不可用时回退为私有服务器）",
	},
	"lsp.formatOnWrite": {
		label: "写入时格式化",
		description: "写入代码文件后使用 LSP 自动格式化",
	},
	"lsp.diagnosticsOnWrite": {
		label: "写入时返回诊断",
		description: "写入代码文件后返回 LSP 诊断信息",
	},
	"lsp.diagnosticsOnEdit": {
		label: "编辑时返回诊断",
		description: "编辑代码文件后返回 LSP 诊断信息",
	},
	"lsp.diagnosticsDeduplicate": {
		label: "去重诊断信息",
		description: "抑制某文件已展示过的编辑后 LSP 诊断；只呈现新增或变化的部分",
	},
};
